# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='identificador')),
                ('longitude', models.CharField(max_length=10, verbose_name='longitude')),
                ('latitude', models.CharField(max_length=10, verbose_name='latitude')),
                ('setcens', models.CharField(max_length=15, verbose_name='setor censitário')),
                ('areap', models.CharField(max_length=13, verbose_name='área de ponderação')),
                ('coddist', models.CharField(max_length=9, verbose_name='código do distrito conforme ibge')),
                ('distrito', models.CharField(max_length=18, verbose_name='distrito municipal')),
                ('codsubpref', models.CharField(max_length=2, verbose_name='código da subprefeitura')),
                ('subpref', models.CharField(max_length=25, verbose_name='subprefeitura')),
                ('regiao5', models.CharField(max_length=6, verbose_name='região conforme divisão do município em 5 áreas')),
                ('regiao8', models.CharField(max_length=7, verbose_name='região conforme divisão do município em 8 áreas')),
                ('nome_feira', models.CharField(max_length=30, verbose_name='nome da feira livre')),
                ('registro', models.CharField(max_length=6, verbose_name='registro da feira livre')),
                ('logradouro', models.CharField(max_length=34, verbose_name='logradouro')),
                ('numero', models.CharField(max_length=5, verbose_name='número')),
                ('bairro', models.CharField(max_length=20, verbose_name='bairro')),
                ('referencia', models.CharField(max_length=24, verbose_name='ponto de referência')),
            ],
        ),
    ]
